name: market-scanner

on:
schedule:
- cron: '*/5 * * * *' # every 5 minutes
workflow_dispatch: # allow manual run

jobs:
scan:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
with:
persist-credentials: true

- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.10'

- name: Install dependencies
run: python -m pip install --upgrade pip && pip install requests yfinance pandas

- name: Run scanner
env:
FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
run: python scanner.py

- name: Commit state.json back (persist hotlist & alerts)
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
if [ -f state.json ]; then
git add state.json || true
git commit -m "Update scanner state [skip ci]" || echo "No changes to commit"
git push origin HEAD || echo "Push failed or no changes"
else
echo "No state.json to commit"
